### ISSUE TITLE
Tábla létrehozása a tétekhez, tétek letárolása, módosítása

### ISSUE THREAD

**Issue by PeterffyZoltan** [PeterffyZoltan/Rulett#1]
Tábla létrehozása, aminek celláira kattintásakor a zsetonokkal kiválasztott tét eltárolásra kerül egy dictionaryben a nyertes szorzóval felszorozva (kulcs: szám,szín,tucat stb; érték: tét * szorzó; pl: 8 : 100*35). A tétek ekkor levonásra kerülnek a játékos pénzéből. A már megtett téteket egy gomb segítségével lehet visszavonni(a szorzóval vissza kell osztani!). A kipörgetett számot meg kell nézni, hogy benne van- e a tétek dictionary kulcsaiban és amennyiben igen, a játékos pénzéhez hozzá kell adni a hozzá tartozó értéket. Ha a tábla egyik cellájára visszük az egeret, más színnel mutatja mire fogjuk rakni a tétet.

**Comment by sariandras** [comment]
Tábla létrehozása, aminek celláira kattintásakor a zsetonokkal kiválasztott tét eltárolásra kerül egy dictionaryben a nyertes szorzóval felszorozva (kulcs: szám,szín,tucat stb; érték: tét * szorzó; pl: 8 : 100*35).  A tétek ekkor levonásra kerülnek a játékos pénzéből. A már megtett téteket egy gomb segítségével lehet visszavonni(a szorzóval vissza kell osztani!). A kipörgetett számot meg kell nézni, hogy benne van- e a tétek dictionary kulcsaiban és amennyiben igen, a játékos pénzéhez hozzá kell adni a hozzá tartozó értéket. Ha a tábla egyik cellájára visszük az egeret, más színnel mutatja mire fogjuk rakni a tétet.

**Comment by sariandras** [comment]
35e09137c08d0062d072f745f9d411f441cd0a36

**Comment by sariandras** [comment]
26b128b8dd55118570eb4fe4012821418119a444

**Comment by sariandras** [comment]
99263c14b3a9cbabe982cc44ef2c341a999ac141

**Comment by sariandras** [comment]
06e4de242ea069c114a89125744f839bb3eddbb0

**Comment by sariandras** [comment]
4df712cf5bd464a4bda1e0f24e7ca187154688e1

**Comment by sariandras** [comment]
e129941662c500bcc6ec06e518e11af970dc7b17

**Comment by sariandras** [comment]
Tábla véglegesen készen van
